# Generated by Django 2.2.5 on 2020-11-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201102_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('kr', 'Korean'), ('fr', 'France'), ('chi', 'Chines'), ('jap', 'Japanes')], max_length=10, null=True),
        ),
    ]
